version: 2.1

integration_test_filters: &integration_test_filters
  branches:
    ignore: /.*/
  tags:
    only: /(integration|master)-.*/

orb_promotion_filters: &orb_promotion_filters
  branches:
    ignore: /.*/
  tags:
    only: /^(major|minor|patch)-release-v\d+\.\d+\.\d+$/

orbs:
  cli: circleci/circleci-cli@0.1.2
  docker-image: stack-fintech/docker-image@dev:alpha
  orb-tools: circleci/orb-tools@7.3.0
  queue: eddiewebb/queue@1.1.2

executors:
  test:
    machine:
      enabled: true
    working_directory: ~/repo

jobs:
  pre-orb-promotion-check:
    executor: test
    steps:
      - checkout
      - run:
          name: Check that this is a master branch commit
          command: |
            git clone "$CIRCLE_REPOSITORY_URL" repository
            cd repository
            git branch --contains ${CIRCLE_SHA1} | grep "master"
  promote-orb-into-production:
    parameters:
      orb-name:
        type: string
        description: |
          Semver-less name of the orb to be promoted into production
      orb-ref:
        type: string
        description: |
          Version information of the orb to be promoted into production
    executor: cli/default
    steps:
      - checkout
      - run:
          name: Promote dev orb to production
          command: |
            RELEASE_TYPE=''
            if [[ "${CIRCLE_TAG}" =~ major-release-* ]]; then
              RELEASE_TYPE='major'
            elif [[ "${CIRCLE_TAG}" =~ minor-release-* ]]; then
              RELEASE_TYPE='minor'
            elif [[ "${CIRCLE_TAG}" =~ patch-release-* ]]; then
              RELEASE_TYPE='patch'
            fi
            if [ -n "${RELEASE_TYPE}" ]; then
              circleci orb publish promote \
              <<parameters.orb-name>>@<<parameters.orb-ref>> \
              ${RELEASE_TYPE} --token \
              ${CIRCLE_TOKEN}
            fi
workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint:
          context: image-builder
      - orb-tools/pack:
          context: image-builder
          requires:
            - orb-tools/lint
      - queue/block_workflow:
          consider-branch: false
          time: "60"
          requires:
            - orb-tools/pack
      - orb-tools/publish-dev:
          orb-name: stack-fintech/docker-image
          context: orb-publishing
          requires:
            - queue/block_workflow
  # Tag-triggered workflow to promote a dev orb into production.
  # The tag is expected to have been applied manually.
  production-orb-publishing:
    jobs:
      - pre-orb-promotion-check:
          filters: *orb_promotion_filters
      - hold-for-approval:
          type: approval
          requires:
            - pre-orb-promotion-check
          filters: *orb_promotion_filters
      - promote-orb-into-production:
          orb-name: stack-fintech/docker-image
          orb-ref: dev:${CIRCLE_SHA1:0:7}
          context: orb-publishing
          requires:
            - hold-for-approval
          filters: *orb_promotion_filters
